# Generated by Django 5.1.4 on 2025-02-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_method_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="method_payment",
            field=models.CharField(
                choices=[("наличные", "Наличные"), ("перевод на счёт", "Перевод на счёт")],
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Эоектронная почта"),
        ),
    ]
