# Generated by Django 5.1.4 on 2025-02-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_method_payment_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="sum_payment",
            field=models.PositiveIntegerField(max_length=100, verbose_name="Сумма платежа"),
        ),
    ]
