# Generated by Django 5.1.4 on 2025-02-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payments_sum_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="sum_payment",
            field=models.PositiveIntegerField(verbose_name="Сумма платежа"),
        ),
    ]
