# Generated by Django 5.1.4 on 2025-02-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0011_alter_payment_link_on_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name="Описание курса"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name="Описание урока"),
        ),
    ]
