# Generated by Django 5.1.4 on 2025-02-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_alter_course_description_alter_lesson_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Название курса"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Название урока"),
        ),
    ]
