# Generated by Django 5.1.4 on 2025-02-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0013_alter_course_name_alter_lesson_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True, verbose_name="цена"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название курса"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True, verbose_name="цена"),
        ),
    ]
