# Generated by Django 5.1.4 on 2025-02-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0014_alter_course_amount_alter_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="цена"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="цена"),
        ),
    ]
